AnthillTendersBundle\Entity\TendersCategory:
    type: entity
    table: null
    repositoryClass: AnthillTendersBundle\Entity\TendersCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name_ru:
            type: string
            length: 255
        name_ua:
            type: string
            length: 255
        name_en:
            type: string
            length: 255
    lifecycleCallbacks: {  }
