<?php

namespace AnthillTendersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TendersCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TendersCategoryRepository extends EntityRepository
{
    public function getAllCategories($locale){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AnthillTendersBundle:TendersCategory p ORDER BY p.name_'.$locale.' ASC'
            )->getArrayResult();
    }
}
