<?php

namespace AnthillTendersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TendersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TendersRepository extends EntityRepository
{
    public function getAllTenders(){
        return $this->getEntityManager()
            ->createQuery(
            'SELECT p FROM AnthillTendersBundle:Tenders p ORDER BY p.id DESC'
            )->getArrayResult();
    }

    public function getTendersPaginatorAll($tenderbox){
        $dql   = "SELECT a FROM AnthillTendersBundle:Tenders a";
        $query = $tenderbox->getEntity()->createQuery($dql);
        return $tenderbox->getPaginator()->paginate(
            $query,
            $tenderbox->getRequest()->query->getInt('page', $tenderbox->getPage()),
            $tenderbox->getMAxCount()
        );
    }

    public function getTendersPaginator($tenderbox){
        $data = $tenderbox->getData();
        $end = new \DateTime;
        if(isset($data['date_end'])){
            $end = new \DateTime($data['date_end']);
            unset($data['date_end']);
        }
        $qb = $tenderbox->getEntity()->createQueryBuilder()
                    ->select('a')
                    ->from('AnthillTendersBundle:Tenders', 'a')
                    ->where("a.dateEnd > '".$end->format("Y-m-d H:i:s")."'");
        if(isset($data['category'])){
            $orX = $qb->expr()->orX();
            foreach($data['category'] as $key => $value){
                $orX->add( 'a.category='.$value);
            }
            $qb->andWhere($orX);
        }
        if(isset($data['company'])){
            $qb->andWhere('a.company LIKE :company')
                ->setParameter('company','%'.trim($data['company']).'%')
                ->getQuery();
        }
        if(isset($data['name'])){
            $qb->andWhere('a.name LIKE :name')
                ->setParameter('name','%'.trim($data['name']).'%')
                ->getQuery();
        }
        if(isset($data['date_start'])){
            $qb->andWhere('a.dateStart='.$data['date_start']);
        }
        $qb->orderBy("a.dateStart","desc");
        return $tenderbox->getPaginator()->paginate(
            $qb,
            $tenderbox->getRequest()->query->getInt('page', $tenderbox->getPage()),
            $tenderbox->getMAxCount()
        );
    }
}