services:
    sonata.admin.post:
        class: AnthillAdminBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AnthillAdminBundle\Entity\Post
            - AnthillAdminBundle:PostAdmin
        calls:
            - [ setTranslationDomain, [AnthillAdminBundle]]